### ISSUE TITLE
level:error

### ISSUE THREAD

**Issue by olimaz** [Grimthorr/laravel-toast#2]
The default level "error" should point to "danger" since the class should be "alert-danger" and not "alert-error".  Currently it is "error"=>"error"

While a patch is released, this can be easily corrected by changing the corresponding value in /config/laravel-toast.php

**Comment by Grimthorr** [comment]
Thanks! This is true if you're using the `messages.blade.php` view, but if you're using the Toastr plugin from the `messages-jquery.blade.php` view the error level needs to be "error" rather than "danger".

I think this will just need to be adjusted depending on what view you want to use.
