### ISSUE TITLE
Is there a possible way to call this toast from ajax

### ISSUE THREAD

**Issue by Arunchild** [Grimthorr/laravel-toast#3]
Using Laravel 5.4 and submitting form via ajax. Is there a possible way calling this function from ajax

**Comment by Grimthorr** [comment]
What function do you want to call from Ajax? I guess you could create a route that calls `Toast::message('message', 'level', 'title')` and have the Ajax request open the URL for that route, but that wouldn't display the toast straight away.

If you just want to show a toast message on completion of the Ajax request, you could return a message from the request and pop your own toast by calling the underlying Javascript library ([toastr](https://github.com/CodeSeven/toastr)), something like: `toastr["success"]("message","title");`. You can see how this is called for this package at: [messages-jquery.blade.php](https://github.com/Grimthorr/laravel-toast/blob/master/views/messages-jquery.blade.php).
