### ISSUE TITLE
laravel-toast.php

### ISSUE THREAD

**Issue by Elmzelji** [Grimthorr/laravel-toast#6]
Didn't find laravel-toast.php in the config folder? i did run the php artisan vendor publish but nothing shows on the config folder

**Comment by yoeunes** [comment]
@Elmzelji you could take a look at this new laravel 5 toast package
https://github.com/yoeunes/toastr

**Comment by Grimthorr** [comment]
What version of Laravel are you using? Running `php artisan vendor:publish --provider="Grimthorr\LaravelToast\ServiceProvider" --tag="config"` should publish the package's config file to the Laravel config directory.

You can also try changing the config `laravel-toast.levels` value directly by using something like:

```php
config('laravel-toast.levels', array(
        'info' => 'info',
        'success' => 'success',
        'error' => 'error',
        'warning' => 'warning',
        'default' => 'info'
    )
);
```
